### ISSUE TITLE
Error occurred while trying to proxy request 

### ISSUE THREAD

**Issue by k0fi** [Chanran/vueSocketChatroom#2]
Hello,

I get this error while trying to run the dev:

`[HPM] Error occurred while trying to proxy request /api/testlogin from localhost:8080 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

I tried other port than 3000 but get the same error. How can I fix it?

**Comment by Chanran** [comment]
Hey,glad to see you using my system.

`
[HPM] Error occurred while trying to proxy request /api/testlogin from localhost:8080 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
`

You missed up a command in the readme.

`npm run server # open another terminal`
